"""
historique_demo.py — Donnees pre-remplies pour le mode demo de l historique.
Fournit 2 AG pour Copropriete Les Acacias (2023 + 2024) et 1 AG pour chaque autre entite.
Permet de tester dossiers, comparaison N/N-1 et export sans cle API.
"""

# ── AG Copropriete Les Acacias — 2023 ────────────────────────────────────────
AG_ACACIAS_2023 = {
    "meta": {
        "version": "2.0",
        "genere_par": "AG Assistant — donnees demo",
        "niveau_confiance_global": "demo",
        "avertissement": "Donnees de demonstration uniquement.",
    },
    "type_ag": "copropriete",
    "informations_generales": {
        "entite": "Copropriete Les Acacias",
        "date": "17/06/2023",
        "lieu": "Salle communale, 12 rue des Lilas, 75012 Paris",
        "type_assemblee": "AG ordinaire annuelle",
        "heure_ouverture": "18:30",
        "heure_cloture": "20:05",
        "president_seance": "Maitre Lefebvre (Cabinet Durand et Associes)",
        "secretaire": "non mentionne dans la transcription",
        "scrutateurs": [],
    },
    "participants": {
        "presents": [{"nom": "12 coproprietaires", "qualite": "coproprietaire", "voix_ou_parts": 570, "observations": ""}],
        "representes": [{"mandant": "3 coproprietaires", "mandataire": "par procuration", "voix_ou_parts": None}],
        "absents_excuses": [],
        "total_presents": 12,
        "total_representes": 3,
        "total_votants": 15,
        "total_voix": 570,
        "quorum_requis": "Plus de la moitie des tantiemes (>500/1000)",
        "quorum_calcule": 570,
        "quorum_atteint": True,
        "base_legale_quorum": "Loi du 10 juillet 1965",
        "observations_quorum": "570 milliemes sur 1000 representes — quorum atteint",
    },
    "ordre_du_jour": [
        {"numero": 1, "intitule": "Approbation des comptes de l exercice 2022", "traite": True},
        {"numero": 2, "intitule": "Vote du budget previsionnel 2023-2024", "traite": True},
        {"numero": 3, "intitule": "Remplacement de la chaudiere collective", "traite": True},
        {"numero": 4, "intitule": "Questions diverses", "traite": True},
    ],
    "resolutions": [
        {
            "numero": 1,
            "titre": "Approbation des comptes annuels",
            "description": "Approbation des comptes de l exercice 2022. Charges totales : 46 200 euros. Solde crediteur : 1 800 euros.",
            "locuteur_proposition": "Maitre Lefebvre",
            "points_discussion": ["Comptes conformes au budget vote"],
            "timestamps": {"debut": None, "fin": None},
            "votes": {"pour": 15, "contre": 0, "abstentions": 0, "non_participants": None, "unite": "voix"},
            "majorite_requise": "article_24",
            "majorite_atteinte": True,
            "statut": "adoptee",
            "base_legale": "Article 24 loi 10 juillet 1965",
            "mentions_obligatoires_presentes": True,
            "niveau_confiance": "eleve",
            "sections_incertaines": [],
        },
        {
            "numero": 2,
            "titre": "Budget previsionnel annuel",
            "description": "Approbation du budget previsionnel 2023-2024 a 48 300 euros, soit +4,5%.",
            "locuteur_proposition": "Maitre Lefebvre",
            "points_discussion": ["Hausse de 4,5% liee aux couts energetiques"],
            "timestamps": {"debut": None, "fin": None},
            "votes": {"pour": 13, "contre": 1, "abstentions": 1, "non_participants": None, "unite": "voix"},
            "majorite_requise": "article_24",
            "majorite_atteinte": True,
            "statut": "adoptee",
            "base_legale": "Article 24 loi 10 juillet 1965",
            "mentions_obligatoires_presentes": True,
            "niveau_confiance": "eleve",
            "sections_incertaines": [],
        },
        {
            "numero": 3,
            "titre": "Remplacement de la chaudiere collective",
            "description": "Vote pour le remplacement de la chaudiere (1998) pour 22 500 euros. La resolution a ete soumise pour la premiere fois.",
            "locuteur_proposition": "Maitre Lefebvre",
            "points_discussion": ["Chaudiere vieillissante — premier vote"],
            "timestamps": {"debut": None, "fin": None},
            "votes": {"pour": 7, "contre": 6, "abstentions": 2, "non_participants": None, "unite": "voix"},
            "majorite_requise": "article_25",
            "majorite_atteinte": False,
            "statut": "rejetee",
            "base_legale": "Article 25 loi 10 juillet 1965",
            "mentions_obligatoires_presentes": True,
            "niveau_confiance": "eleve",
            "sections_incertaines": [],
        },
    ],
    "decisions_finales": [
        {"resolution": 1, "titre": "Comptes 2022", "statut": "adoptee", "effet": "Comptes 2022 approuves"},
        {"resolution": 2, "titre": "Budget 2023-2024", "statut": "adoptee", "effet": "Budget de 48 300 euros vote"},
        {"resolution": 3, "titre": "Chaudiere", "statut": "rejetee", "effet": "Remplacement refuse — reporté à 2024"},
    ],
    "points_divers": ["Madame Petit signale une infiltration au 3eme etage."],
    "conformite_legale": {
        "mentions_obligatoires_pv": {"date_et_lieu": True, "president_seance": True, "liste_presents": True, "quorum_constate": True, "ordre_du_jour": True, "resultats_votes": True},
        "alertes": ["Secretaire de seance non identifie"],
        "recommandations": ["Identifier le secretaire de seance"],
    },
    "observations_juridiques": "AG valide 2023. Resolution chaudiere rejetee — soumise a nouveau en 2024.",
    "niveaux_confiance_sections": {"participants": 95, "votes": 92, "quorum": 88, "convocation": 70, "ordre_du_jour": 98},
    "diarization": [],
}

# ── AG Copropriete Les Acacias — 2024 ────────────────────────────────────────
AG_ACACIAS_2024 = {
    "meta": {
        "version": "2.0",
        "genere_par": "AG Assistant — donnees demo",
        "niveau_confiance_global": "demo",
        "avertissement": "Donnees de demonstration uniquement.",
    },
    "type_ag": "copropriete",
    "informations_generales": {
        "entite": "Copropriete Les Acacias",
        "date": "15/06/2024",
        "lieu": "Salle communale, 12 rue des Lilas, 75012 Paris",
        "type_assemblee": "AG ordinaire annuelle",
        "heure_ouverture": "18:30",
        "heure_cloture": "20:10",
        "president_seance": "Maitre Lefebvre (Cabinet Durand et Associes)",
        "secretaire": "non mentionne dans la transcription",
        "scrutateurs": [],
    },
    "participants": {
        "presents": [{"nom": "14 coproprietaires", "qualite": "coproprietaire", "voix_ou_parts": 612, "observations": ""}],
        "representes": [{"mandant": "4 coproprietaires", "mandataire": "par procuration", "voix_ou_parts": None}],
        "absents_excuses": [],
        "total_presents": 14,
        "total_representes": 4,
        "total_votants": 18,
        "total_voix": 612,
        "quorum_requis": "Plus de la moitie des tantiemes (>500/1000)",
        "quorum_calcule": 612,
        "quorum_atteint": True,
        "base_legale_quorum": "Loi du 10 juillet 1965",
        "observations_quorum": "612 milliemes sur 1000 representes — quorum atteint",
    },
    "ordre_du_jour": [
        {"numero": 1, "intitule": "Approbation des comptes de l exercice 2023", "traite": True},
        {"numero": 2, "intitule": "Vote du budget previsionnel 2024-2025", "traite": True},
        {"numero": 3, "intitule": "Travaux de ravalement de facade", "traite": True},
        {"numero": 4, "intitule": "Remplacement de la chaudiere collective", "traite": True},
        {"numero": 5, "intitule": "Questions diverses", "traite": True},
    ],
    "resolutions": [
        {
            "numero": 1,
            "titre": "Approbation des comptes annuels",
            "description": "Approbation des comptes de l exercice 2023. Charges totales : 48 320 euros. Solde crediteur : 2 150 euros.",
            "locuteur_proposition": "Maitre Lefebvre",
            "points_discussion": ["Comptes conformes au budget vote"],
            "timestamps": {"debut": None, "fin": None},
            "votes": {"pour": 16, "contre": 1, "abstentions": 1, "non_participants": None, "unite": "voix"},
            "majorite_requise": "article_24",
            "majorite_atteinte": True,
            "statut": "adoptee",
            "base_legale": "Article 24 loi 10 juillet 1965",
            "mentions_obligatoires_presentes": True,
            "niveau_confiance": "eleve",
            "sections_incertaines": [],
        },
        {
            "numero": 2,
            "titre": "Budget previsionnel annuel",
            "description": "Approbation du budget previsionnel 2024-2025 a 51 000 euros, soit +5,5%.",
            "locuteur_proposition": "Maitre Lefebvre",
            "points_discussion": ["Hausse 5,5% liee aux couts energetiques"],
            "timestamps": {"debut": None, "fin": None},
            "votes": {"pour": 15, "contre": 2, "abstentions": 1, "non_participants": None, "unite": "voix"},
            "majorite_requise": "article_24",
            "majorite_atteinte": True,
            "statut": "adoptee",
            "base_legale": "Article 24 loi 10 juillet 1965",
            "mentions_obligatoires_presentes": True,
            "niveau_confiance": "eleve",
            "sections_incertaines": [],
        },
        {
            "numero": 3,
            "titre": "Travaux de ravalement de facade",
            "description": "Approbation des travaux de ravalement avec Facades Pro pour 87 000 euros TTC.",
            "locuteur_proposition": "Maitre Lefebvre",
            "points_discussion": ["Devis Facades Pro retenu par le conseil syndical"],
            "timestamps": {"debut": None, "fin": None},
            "votes": {"pour": 13, "contre": 4, "abstentions": 1, "non_participants": None, "unite": "voix"},
            "majorite_requise": "article_25",
            "majorite_atteinte": True,
            "statut": "adoptee",
            "base_legale": "Article 25 loi 10 juillet 1965",
            "mentions_obligatoires_presentes": True,
            "niveau_confiance": "eleve",
            "sections_incertaines": [],
        },
        {
            "numero": 4,
            "titre": "Remplacement de la chaudiere collective",
            "description": "Deuxieme soumission du remplacement chaudiere pour 22 500 euros. Rejete a nouveau.",
            "locuteur_proposition": "Maitre Lefebvre",
            "points_discussion": ["Deuxieme vote consecutif — toujours rejete"],
            "timestamps": {"debut": None, "fin": None},
            "votes": {"pour": 9, "contre": 7, "abstentions": 2, "non_participants": None, "unite": "voix"},
            "majorite_requise": "article_25",
            "majorite_atteinte": False,
            "statut": "rejetee",
            "base_legale": "Article 25 loi 10 juillet 1965",
            "mentions_obligatoires_presentes": True,
            "niveau_confiance": "eleve",
            "sections_incertaines": [],
        },
    ],
    "decisions_finales": [
        {"resolution": 1, "titre": "Comptes 2023", "statut": "adoptee", "effet": "Comptes 2023 approuves"},
        {"resolution": 2, "titre": "Budget 2024-2025", "statut": "adoptee", "effet": "Budget de 51 000 euros vote"},
        {"resolution": 3, "titre": "Ravalement facade", "statut": "adoptee", "effet": "Travaux Facades Pro autorises — 87 000 euros"},
        {"resolution": 4, "titre": "Chaudiere", "statut": "rejetee", "effet": "Remplacement refuse — 2eme refus consecutif"},
    ],
    "points_divers": [
        "Madame Petit signale un probleme d humidite au sous-sol.",
        "Monsieur Bernard demande le changement du digicode.",
    ],
    "conformite_legale": {
        "mentions_obligatoires_pv": {"date_et_lieu": True, "president_seance": True, "liste_presents": True, "quorum_constate": True, "ordre_du_jour": True, "resultats_votes": True},
        "alertes": ["Secretaire de seance non identifie"],
        "recommandations": ["Identifier le secretaire de seance"],
    },
    "observations_juridiques": "AG valide 2024. Resolution chaudiere rejetee pour la 2eme annee consecutive.",
    "niveaux_confiance_sections": {"participants": 95, "votes": 91, "quorum": 78, "convocation": 65, "ordre_du_jour": 98},
    "diarization": [],
}

# ── AG Association Elan Vitry — 2024 ─────────────────────────────────────────
AG_ELAN_VITRY_2024 = {
    "meta": {"version": "2.0", "genere_par": "AG Assistant — donnees demo", "niveau_confiance_global": "demo", "avertissement": "Donnees de demonstration uniquement."},
    "type_ag": "association",
    "informations_generales": {"entite": "Association Sportive Elan Vitry", "date": "28/09/2024", "lieu": "Gymnase municipal de Vitry-sur-Seine", "type_assemblee": "AG extraordinaire", "heure_ouverture": "19:00", "heure_cloture": "20:25", "president_seance": "Sophie Marchand", "secretaire": "non mentionne", "scrutateurs": []},
    "participants": {"presents": [{"nom": "43 membres", "qualite": "membre", "voix_ou_parts": 43, "observations": ""}], "representes": [{"mandant": "8 membres", "mandataire": "procurations", "voix_ou_parts": 8}], "absents_excuses": [], "total_presents": 43, "total_representes": 8, "total_votants": 51, "total_voix": 51, "quorum_requis": "50% + 1 soit 44", "quorum_calcule": 51, "quorum_atteint": True, "base_legale_quorum": "Statuts", "observations_quorum": "Quorum atteint"},
    "ordre_du_jour": [{"numero": 1, "intitule": "Modification cotisations", "traite": True}, {"numero": 2, "intitule": "Acquisition equipements sportifs", "traite": True}],
    "resolutions": [
        {"numero": 1, "titre": "Modification article 12 cotisations", "description": "Hausse cotisation adultes 80->110 euros, enfants 50->65 euros.", "locuteur_proposition": "Sophie Marchand", "points_discussion": ["Tarif solidaire 80 euros sur demande cree"], "timestamps": {"debut": None, "fin": None}, "votes": {"pour": 44, "contre": 5, "abstentions": 2, "non_participants": None, "unite": "voix"}, "majorite_requise": "deux_tiers", "majorite_atteinte": True, "statut": "adoptee", "base_legale": "Statuts loi 1901", "mentions_obligatoires_presentes": True, "niveau_confiance": "eleve", "sections_incertaines": []},
        {"numero": 2, "titre": "Acquisition equipements sportifs", "description": "Achat 2 buts football + dossards — 3 200 euros.", "locuteur_proposition": "Bureau", "points_discussion": [], "timestamps": {"debut": None, "fin": None}, "votes": {"pour": 49, "contre": 0, "abstentions": 2, "non_participants": None, "unite": "voix"}, "majorite_requise": "simple", "majorite_atteinte": True, "statut": "adoptee", "base_legale": "Statuts", "mentions_obligatoires_presentes": True, "niveau_confiance": "eleve", "sections_incertaines": []},
    ],
    "decisions_finales": [{"resolution": 1, "titre": "Cotisations", "statut": "adoptee", "effet": "Nouveaux tarifs au 1er janvier 2025"}, {"resolution": 2, "titre": "Equipements", "statut": "adoptee", "effet": "Achat autorise"}],
    "points_divers": ["Prochaine AG ordinaire mars 2025"],
    "conformite_legale": {"mentions_obligatoires_pv": {"date_et_lieu": True, "president_seance": True, "liste_presents": True, "quorum_constate": True, "ordre_du_jour": True, "resultats_votes": True}, "alertes": ["Secretaire non identifie"], "recommandations": ["Faire signer PV par president et secretaire"]},
    "observations_juridiques": "AGE valide. Quorum atteint. 2 resolutions adoptees.",
    "niveaux_confiance_sections": {"participants": 93, "votes": 95, "quorum": 90, "convocation": 65, "ordre_du_jour": 98},
    "diarization": [],
}

# ── AG SAS Innov Tech — 2024 ──────────────────────────────────────────────────
AG_INNOVTECH_2024 = {
    "meta": {"version": "2.0", "genere_par": "AG Assistant — donnees demo", "niveau_confiance_global": "demo", "avertissement": "Donnees de demonstration uniquement."},
    "type_ag": "pme_sas",
    "informations_generales": {"entite": "SAS Innov Tech", "date": "30/04/2024", "lieu": "45 avenue de la Republique, 69003 Lyon", "type_assemblee": "AGO", "heure_ouverture": "14:00", "heure_cloture": "16:15", "president_seance": "Alexandre Fontaine", "secretaire": "non mentionne", "scrutateurs": []},
    "participants": {"presents": [{"nom": "Alexandre Fontaine", "qualite": "associe", "voix_ou_parts": 600, "observations": ""}, {"nom": "Nadia Benchikh", "qualite": "associe", "voix_ou_parts": 300, "observations": ""}, {"nom": "Thomas Roux", "qualite": "associe", "voix_ou_parts": 250, "observations": ""}, {"nom": "Claire Vidal", "qualite": "associe", "voix_ou_parts": 200, "observations": ""}, {"nom": "Marc Lejeune", "qualite": "associe", "voix_ou_parts": 150, "observations": ""}], "representes": [], "absents_excuses": [], "total_presents": 5, "total_representes": 0, "total_votants": 5, "total_voix": 1500, "quorum_requis": "Selon statuts SAS", "quorum_calcule": 1500, "quorum_atteint": True, "base_legale_quorum": "Statuts SAS Innov Tech", "observations_quorum": "100% des parts representees"},
    "ordre_du_jour": [{"numero": 1, "intitule": "Approbation comptes 2023", "traite": True}, {"numero": 2, "intitule": "Affectation resultat", "traite": True}, {"numero": 3, "intitule": "Renouvellement CAC", "traite": True}, {"numero": 4, "intitule": "Autorisation emprunt", "traite": True}],
    "resolutions": [
        {"numero": 1, "titre": "Approbation comptes annuels 2023", "description": "CA 2,3M euros (+18%). Resultat net 142 000 euros.", "locuteur_proposition": "Thomas Roux", "points_discussion": ["Progression 18% CA"], "timestamps": {"debut": "14:00", "fin": None}, "votes": {"pour": 1500, "contre": 0, "abstentions": 0, "non_participants": None, "unite": "parts"}, "majorite_requise": "selon_statuts", "majorite_atteinte": True, "statut": "adoptee", "base_legale": "Statuts SAS", "mentions_obligatoires_presentes": True, "niveau_confiance": "eleve", "sections_incertaines": []},
        {"numero": 2, "titre": "Affectation du resultat", "description": "14 200 euros reserve legale + 50 000 euros reserves + 77 800 euros dividendes.", "locuteur_proposition": "Alexandre Fontaine", "points_discussion": [], "timestamps": {"debut": None, "fin": None}, "votes": {"pour": 1500, "contre": 0, "abstentions": 0, "non_participants": None, "unite": "parts"}, "majorite_requise": "selon_statuts", "majorite_atteinte": True, "statut": "adoptee", "base_legale": "Statuts SAS", "mentions_obligatoires_presentes": True, "niveau_confiance": "eleve", "sections_incertaines": []},
        {"numero": 3, "titre": "Renouvellement mandat commissaire aux comptes", "description": "Renouvellement Ernst et Martin pour 6 exercices.", "locuteur_proposition": "Alexandre Fontaine", "points_discussion": ["Marc Lejeune vote contre"], "timestamps": {"debut": None, "fin": None}, "votes": {"pour": 1350, "contre": 150, "abstentions": 0, "non_participants": None, "unite": "parts"}, "majorite_requise": "selon_statuts", "majorite_atteinte": True, "statut": "adoptee", "base_legale": "Statuts SAS", "mentions_obligatoires_presentes": True, "niveau_confiance": "eleve", "sections_incertaines": []},
        {"numero": 4, "titre": "Autorisation emprunt bancaire 200 000 euros", "description": "Emprunt Credit Industriel de Lyon — 200 000 euros sur 5 ans.", "locuteur_proposition": "Alexandre Fontaine", "points_discussion": [], "timestamps": {"debut": None, "fin": "16:15"}, "votes": {"pour": 1500, "contre": 0, "abstentions": 0, "non_participants": None, "unite": "parts"}, "majorite_requise": "selon_statuts", "majorite_atteinte": True, "statut": "adoptee", "base_legale": "Statuts SAS", "mentions_obligatoires_presentes": True, "niveau_confiance": "eleve", "sections_incertaines": []},
    ],
    "decisions_finales": [{"resolution": 1, "titre": "Comptes 2023", "statut": "adoptee", "effet": "Comptes approuves"}, {"resolution": 2, "titre": "Affectation resultat", "statut": "adoptee", "effet": "Dividendes 77 800 euros"}, {"resolution": 3, "titre": "CAC", "statut": "adoptee", "effet": "Mandat renouvele 6 ans"}, {"resolution": 4, "titre": "Emprunt", "statut": "adoptee", "effet": "200 000 euros autorises"}],
    "points_divers": [],
    "conformite_legale": {"mentions_obligatoires_pv": {"date_et_lieu": True, "president_seance": True, "liste_presents": True, "quorum_constate": True, "ordre_du_jour": True, "resultats_votes": True}, "alertes": ["Secretaire non mentionne"], "recommandations": ["Faire signer le PV par le president"]},
    "observations_juridiques": "AGO valide. 100% capital represente. 4 resolutions adoptees.",
    "niveaux_confiance_sections": {"participants": 98, "votes": 98, "quorum": 95, "convocation": 75, "ordre_du_jour": 99},
    "diarization": [],
}

# ── Registre des AG demo ──────────────────────────────────────────────────────

DEMO_HISTORIQUE = [
    {
        "analyse": AG_ACACIAS_2023,
        "pv_texte": None,
        "label": "Copropriete Les Acacias — AG 2023",
    },
    {
        "analyse": AG_ACACIAS_2024,
        "pv_texte": None,
        "label": "Copropriete Les Acacias — AG 2024",
    },
    {
        "analyse": AG_ELAN_VITRY_2024,
        "pv_texte": None,
        "label": "Association Sportive Elan Vitry — AGE 2024",
    },
    {
        "analyse": AG_INNOVTECH_2024,
        "pv_texte": None,
        "label": "SAS Innov Tech — AGO 2024",
    },
]
